### ISSUE TITLE
README has outdated info about tables

### ISSUE THREAD

**Issue by cmj2002** [tryfabric/martian#30]
<sub>[Discuss in #**public-issue-30--notion-api-now-supports-tables**](https://slack.com/app_redirect?team=TJ5G67VHU&channel=C03ER2LHRK7)</sub>

https://developers.notion.com/reference/block#table-blocks

Notion API now supports tables. Could you add support of table into martian?(Or you just forgot to edit the README?)

**Comment by EndBug** [comment]
Hi, thanks for opening the issue!
First of all, yep, the README is outdated, thanks for pointing it out

Table support was introduced with #19, and is currently available by setting the `allowUnsupported` option to `true`
Please note that this change was introduced in version 1.2.0, which is available at [`@tryfabric/martian`](https://www.npmjs.com/package/@tryfabric/martian) on npm: we're in the process of moving our open source packages from `@instantish` to `@tryfabric`
There are still a few issues with tables that we need to fix before we put it outside of "unsupported mode"
