### ISSUE TITLE
Question: Does this repo require that we do the logic to determine if it's a block or richtext?

### ISSUE THREAD

**Issue by tommygwu** [tryfabric/martian#62]
If I have markdown that contains blocks and richtext (bullet point with hyperlink), do I have to make that determination and call both markdownToBlocks and markdownToRichText? Is there a way to just let the code make that determination?

**Comment by EndBug** [comment]
Nope :)
Blocks can contain rich text, so the library will handle that automatically: in your case you can just call `markdownToBlocks` and the inner rich text will be parsed as needed

**Comment by tommygwu** [comment]
Thanks for the update!
